In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime 
plt.rc('font', family='AppleGothic')

In [4]:
df = pd.read_csv('/Users/seulalee/OneDrive/MyStudy/210816_엘리스AI트랙/TeamProject1/Team11_NaplessRabbit/project-template/rawdata/시간-지역별배달주문건수/time_area_delivery_freq.csv', index_col=0)
df

/Users/seulalee/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

                  0   1     2         3    4   5
0        2019-08-01   0   강원도       속초시   교동   1
1        2019-08-01   0   경기도  고양시 일산동구  마두동   4
2        2019-08-01   0   경기도  고양시 일산동구  백석동  28
3        2019-08-01   0   경기도  고양시 일산동구  식사동   3
4        2019-08-01   0   경기도  고양시 일산동구  장항동   4
...             ...  ..   ...       ...  ...  ..
2382976  2021-08-31  23  충청남도   천안시 서북구  쌍용동   6
2382977  2021-08-31  23  충청북도       제천시  신백동   6
2382978  2021-08-31  23  충청북도       제천시  신월동   2
2382979  2021-08-31  23  충청북도       제천시  천남동   1
2382980  2021-08-31  23  충청북도       제천시  하소동   4

[2382981 rows x 6 columns]

In [5]:
df.columns=['날짜','시간','광역시도','시군구','읍면동','배달건수']

In [6]:
df

                 날짜  시간  광역시도       시군구  읍면동  배달건수
0        2019-08-01   0   강원도       속초시   교동     1
1        2019-08-01   0   경기도  고양시 일산동구  마두동     4
2        2019-08-01   0   경기도  고양시 일산동구  백석동    28
3        2019-08-01   0   경기도  고양시 일산동구  식사동     3
4        2019-08-01   0   경기도  고양시 일산동구  장항동     4
...             ...  ..   ...       ...  ...   ...
2382976  2021-08-31  23  충청남도   천안시 서북구  쌍용동     6
2382977  2021-08-31  23  충청북도       제천시  신백동     6
2382978  2021-08-31  23  충청북도       제천시  신월동     2
2382979  2021-08-31  23  충청북도       제천시  천남동     1
2382980  2021-08-31  23  충청북도       제천시  하소동     4

[2382981 rows x 6 columns]

In [7]:
df.groupby(['광역시도','시군구','읍면동','날짜','시간']).count().reset_index()

         광역시도  시군구  읍면동          날짜  시간  배달건수
0         강원도  강릉시   교동  2019-08-02  19     1
1         강원도  강릉시   교동  2019-08-03  15     1
2         강원도  강릉시   교동  2019-08-03  16     1
3         강원도  강릉시   교동  2019-08-04  11     1
4         강원도  강릉시   교동  2019-08-04  14     1
...       ...  ...  ...         ...  ..   ...
2382976  충청북도  충주시  호암동  2021-03-11  18     1
2382977  충청북도  충주시  호암동  2021-03-11  19     1
2382978  충청북도  충주시  호암동  2021-03-11  20     1
2382979  충청북도  충주시  호암동  2021-03-11  22     1
2382980  충청북도  충주시  호암동  2021-03-11  23     1

[2382981 rows x 6 columns]

In [8]:
# 각 광역시도, 시군구, 읍면동에서, 날짜를 컬럼을 2019-08-01부터 2021-08-31까지 차례로 도는데
# 만약 매치되는 날짜 컬럼이 없으면 해당 컬럼을 생성해주고, 있으면 그냥 패스

# 1. 일단 매치할 기준 날짜 리스트가 있어야 함 
entire_date = pd.date_range(start='2019-08-01', end='2021-09-01', freq='H')
entire_date = pd.DataFrame(entire_date)
entire_date
# -> 한 시간 단위까지 한번에 생성 되네!!!

                        0
0     2019-08-01 00:00:00
1     2019-08-01 01:00:00
2     2019-08-01 02:00:00
3     2019-08-01 03:00:00
4     2019-08-01 04:00:00
...                   ...
18284 2021-08-31 20:00:00
18285 2021-08-31 21:00:00
18286 2021-08-31 22:00:00
18287 2021-08-31 23:00:00
18288 2021-09-01 00:00:00

[18289 rows x 1 columns]

In [9]:
# 2. for 문으로 모든 지역을 돌아야하니까 일단 위치도 합쳐서 하나의 주소지로 만들자
df['지역'] = df['광역시도'] + '-' + df['시군구']+ '-' + df['읍면동']
df.drop(['광역시도', '시군구', '읍면동'], axis=1, inplace=True)
df

                 날짜  시간  배달건수                지역
0        2019-08-01   0     1        강원도-속초시-교동
1        2019-08-01   0     4  경기도-고양시 일산동구-마두동
2        2019-08-01   0    28  경기도-고양시 일산동구-백석동
3        2019-08-01   0     3  경기도-고양시 일산동구-식사동
4        2019-08-01   0     4  경기도-고양시 일산동구-장항동
...             ...  ..   ...               ...
2382976  2021-08-31  23     6  충청남도-천안시 서북구-쌍용동
2382977  2021-08-31  23     6      충청북도-제천시-신백동
2382978  2021-08-31  23     2      충청북도-제천시-신월동
2382979  2021-08-31  23     1      충청북도-제천시-천남동
2382980  2021-08-31  23     4      충청북도-제천시-하소동

[2382981 rows x 4 columns]

In [10]:
# 3. 기준이 되는 전체달력시간리스트와 비교가 용이하도록 날짜와 시간도 합치기   : '2021-08-30 23:00:00'
# 시간 컬럼 데이터타입이 int64라 str으로 바꿔서 붙임
df['date_time'] = df['날짜']+ " " + df['시간'].apply(str) + ":00:00"
df.drop(['날짜','시간'], axis=1, inplace=True)
df

         배달건수                지역            date_time
0           1        강원도-속초시-교동   2019-08-01 0:00:00
1           4  경기도-고양시 일산동구-마두동   2019-08-01 0:00:00
2          28  경기도-고양시 일산동구-백석동   2019-08-01 0:00:00
3           3  경기도-고양시 일산동구-식사동   2019-08-01 0:00:00
4           4  경기도-고양시 일산동구-장항동   2019-08-01 0:00:00
...       ...               ...                  ...
2382976     6  충청남도-천안시 서북구-쌍용동  2021-08-31 23:00:00
2382977     6      충청북도-제천시-신백동  2021-08-31 23:00:00
2382978     2      충청북도-제천시-신월동  2021-08-31 23:00:00
2382979     1      충청북도-제천시-천남동  2021-08-31 23:00:00
2382980     4      충청북도-제천시-하소동  2021-08-31 23:00:00

[2382981 rows x 3 columns]

In [11]:
# 4. 모든 개별 읍면동에 date_time이 누락된 거 없는지 기준셋entire_date랑 비교를 위해서는
# 모든 개별 읍면동을 for로 하나씩 돌아야 함으로, 일단 '지역'의 unique값으로 list 생성하기
all_areas = df['지역'].unique().tolist()
all_areas

['강원도-속초시-교동',
 '경기도-고양시 일산동구-마두동',
 '경기도-고양시 일산동구-백석동',
 '경기도-고양시 일산동구-식사동',
 '경기도-고양시 일산동구-장항동',
 '경기도-고양시 일산동구-정발산동',
 '경기도-고양시 일산서구-일산동',
 '경기도-고양시 일산서구-탄현동',
 '경기도-광명시-광명동',
 '경기도-광명시-철산동',
 '경기도-광명시-하안동',
 '경기도-시흥시-조남동',
 '경기도-의정부시-가능동',
 '경기도-의정부시-금오동',
 '경기도-의정부시-민락동',
 '경기도-의정부시-신곡동',
 '경기도-의정부시-용현동',
 '경기도-의정부시-의정부동',
 '경기도-의정부시-호원동',
 '경기도-포천시-소흘읍',
 '경상남도-김해시-삼방동',
 '경상남도-김해시-삼정동',
 '경상남도-진주시-계동',
 '경상남도-진주시-본성동',
 '경상남도-진주시-봉곡동',
 '경상남도-진주시-신안동',
 '경상남도-진주시-평거동',
 '대전광역시-동구-성남동',
 '서울특별시-구로구-개봉동',
 '서울특별시-구로구-고척동',
 '서울특별시-구로구-구로동',
 '서울특별시-구로구-오류동',
 '서울특별시-금천구-독산동',
 '서울특별시-마포구-망원동',
 '서울특별시-양천구-목동',
 '서울특별시-영등포구-대림동',
 '서울특별시-영등포구-도림동',
 '서울특별시-영등포구-신길동',
 '서울특별시-영등포구-영등포동',
 '서울특별시-은평구-갈현동',
 '전라남도-순천시-조례동',
 '전라남도-순천시-해룡면',
 '전라북도-전주시 완산구-효자동2가',
 '전라북도-전주시 완산구-효자동3가',
 '제주특별자치도-서귀포시-동홍동',
 '제주특별자치도-서귀포시-서귀동',
 '제주특별자치도-서귀포시-서홍동',
 '충청남도-서산시-동문동',
 '충청남도-서산시-석림동',
 '충청북도-제천시-명동',
 '충청북도-제천시-의림동',
 '충청북도-제천시-장락동',
 '경기도-광명시-소하동',
 '경상남도-진주시-동성동',
 '경상남도-진주시-이현동',
 '경상남도-진주시-중안동',
 '충청북도-제천시-신백동',
 '충청북도-제천시-영천동',
 '경기도-의정부시-녹양동',
 '경상남도-김해시-구산동',
 '경상남도-김해시-어방동',
 '경상남도-김해시-외동',
 '경상남도-진주시-인사동',
 '경상북도-안동시-태화동',
 '경기도-김포시-풍무동',
 '경기도-남양주시-다산동',
 '경기도-안산시 상록구-본오동',
 '경상남도-김해시-봉황동',
 '경상남도-김해시-삼계동',
 '경상남도-김해시-주촌면',
 '경상남도-진주시-상봉동',
 '경상남도-진주시-장대동',
 '경상남도-진주시-칠암동',
 '경상남도-창원시 마산회원구-양덕동',
 '경상남도-창원시 마산회원구-합성동',
 '경상북도-안동시-정하동',
 '대구광역시-서구-비산동',
 '서울특별시-강서구-염창동',
 '서울특별시-강서구-화곡동',
 '서울특별시-구로구-궁동',
 '서울특별시-도봉구-방학동',
 '서울특별시-성북구-정릉동',
 '서울특별시-은평구-대조동',
 '충청북도-제천시-청전동',
 '강원도-속초시-금호동',
 '경기도-고양시 일산동구-중산동',
 '경기도-고양시 일산동구-풍동',
 '경기도-고양시 일산서구-덕이동',
 '경기도-고양시 일산서구-주엽동',
 '경기도-광명시-일직동',
 '경기도-김포시-감정동',
 '경기도-남양주시-별내동',
 '경기도-남양주시-오남읍',
 '경기도-부천시-괴안동',
 '경기도-부천시-옥길동',
 '경기도-시흥시-목감동',
 '경기도-양주시-백석읍',
 '경기도-용인시 처인구-남사면',
 '경기도-의정부시-장암동',
 '경기도-파주시-동패동',
 '경기도-포천시-신읍동',
 '경기도-화성시-산척동',
 '경상남도-김해시-내동',
 '경상남도-김해시-대성동',
 '경상남도-김해시-부원동',
 '경상남도-진주시-대안동',
 '경상남도-진주시-상대동',
 '경상남도-진주시-옥봉동',
 '경상남도-창원시 마산합포구-산호동',
 '경상남도-창원시 마산합포구-상남동',
 '경상남도-창원시 마산합포구-오동동',
 '경상남도-함양군-함양읍',
 '경상북도-안동시-금곡동',
 '경상북도-안동시-삼산동',
 '경상북도-안동시-옥동',
 '경상북도-안동시-옥야동',
 '경상북도-안동시-천리동',
 '대구광역시-달서구-감삼동',
 '대구광역시-달서구-용산동',
 '대구광역시-달서구-이곡동',
 '대구광역시-달성군-다사읍',
 '부산광역시-강서구-명지동',
 '부산광역시-사하구-하단동',
 '서울특별시-강북구-미아동',
 '서울특별시-강서구-공항동',
 '서울특별시-도봉구-도봉동',
 '서울특별시-도봉구-창동',
 '서울특별시-양천구-신정동',
 '서울특별시-영등포구-영등포동1가',
 '서울특별시-은평구-신사동',
 '서울특별시-은평구-역촌동',
 '전라남도-순천시-연향동',
 '전라남도-순천시-왕지동',
 '충청남도-보령시-명천동',
 '충청북도-제천시-강제동',
 '충청북도-제천시-모산동',
 '충청북도-제천시-중앙로1가',
 '충청북도-제천시-중앙로2가',
 '충청북도-제천시-화산동',
 '강원도-속초시-청학동',
 '강원도-원주시-단구동',
 '강원도-원주시-일산동',
 '강원도-원주시-태장동',
 '경기도-시흥시-산현동',
 '경기도-연천군-전곡읍',
 '경기도-평택시-안중읍',
 '경상남도-김해시-서상동',
 '경상남도-창녕군-창녕읍',
 '경상남도-창원시 마산합포구-동성동',
 '광주광역시-동구-소태동',
 '대전광역시-동구-가양동',
 '부산광역시-사하구-당리동',
 '부산광역시-해운대구-반송동',
 '서울특별시-노원구-상계동',
 '서울특별시-도봉구-쌍문동',
 '서울특별시-동작구-신대방동',
 '인천광역시-부평구-청천동',
 '충청남도-서산시-대산읍',
 '충청남도-서산시-읍내동',
 '충청북도-제천시-하소동',
 '강원도-원주시-단계동',
 '강원도-원주시-무실동',
 '경기도-남양주시-평내동',
 '경기도-수원시 권선구-금곡동',
 '경기도-의정부시-낙양동',
 '경상남도-진주시-상평동',
 '대구광역시-서구-내당동',
 '대구광역시-서구-평리동',
 '부산광역시-강서구-신호동',
 '서울특별시-강서구-방화동',
 '서울특별시-동작구-대방동',
 '인천광역시-부평구-산곡동',
 '충청남도-천안시 동남구-청당동',
 '충청북도-청주시 청원구-우암동',
 '강원도-원주시-반곡동',
 '경기도-남양주시-진접읍',
 '경기도-남양주시-호평동',
 '경기도-화성시-오산동',
 '광주광역시-북구-오치동',
 '대구광역시-달서구-파호동',
 '서울특별시-강서구-등촌동',
 '서울특별시-강서구-마곡동',
 '서울특별시-구로구-온수동',
 '전라남도-나주시-빛가람동',
 '충청남도-보령시-죽정동',
 '충청북도-제천시-고암동',
 '경기도-시흥시-논곡동',
 '경기도-파주시-와동동',
 '서울특별시-강서구-내발산동',
 '서울특별시-양천구-신월동',
 '인천광역시-부평구-십정동',
 '전라남도-나주시-중앙동',
 '경기도-파주시-야당동',
 '경상남도-김해시-동상동',
 '경상남도-사천시-벌리동',
 '경상남도-진주시-수정동',
 '경상북도-안동시-용상동',
 '대구광역시-달서구-신당동',
 '서울특별시-강서구-가양동',
 '서울특별시-성북구-길음동',
 '전라남도-여수시-문수동',
 '충청북도-제천시-신월동',
 '강원도-속초시-조양동',
 '경기도-시흥시-은행동',
 '경상남도-진주시-주약동',
 '경상남도-진주시-평안동',
 '경상남도-창원시 마산합포구-신포동1가',
 '경상북도-안동시-광석동',
 '경상북도-안동시-정상동',
 '경상북도-안동시-평화동',
 '서울특별시-구로구-천왕동',
 '서울특별시-서대문구-홍은동',
 '울산광역시-북구-화봉동',
 '충청남도-서산시-예천동',
 '경기도-김포시-사우동',
 '경기도-남양주시-진건읍',
 '경상남도-사천시-향촌동',
 '경상남도-진주시-가좌동',
 '경상남도-진주시-망경동',
 '경상북도-안동시-동부동',
 '경기도-남양주시-퇴계원읍',
 '경상남도-창원시 마산회원구-석전동',
 '부산광역시-사하구-다대동',
 '경기도-화성시-향남읍',
 '경상북도-안동시-율세동',
 '서울특별시-은평구-불광동',
 '충청북도-제천시-천남동',
 '제주특별자치도-제주시-삼도이동',
 '경기도-파주시-목동동',
 '인천광역시-남동구-간석동',
 '충청남도-보령시-동대동',
 '광주광역시-서구-치평동',
 '부산광역시-사하구-장림동',
 '전라북도-군산시-지곡동',
 '강원도-삼척시-교동',
 '경상남도-진주시-초전동',
 '경상북도-구미시-인의동',
 '서울특별시-은평구-구산동',
 '전라북도-군산시-나운동',
 '경상북도-안동시-남부동',
 '강원도-강릉시-교동',
 '강원도-원주시-관설동',
 '경상남도-창원시 마산회원구-구암동',
 '광주광역시-동구-계림동',
 '충청북도-제천시-동현동',
 '제주특별자치도-제주시-아라일동',
 '경상남도-창원시 마산회원구-회원동',
 '서울특별시-관악구-봉천동',
 '서울특별시-관악구-신림동',
 '부산광역시-수영구-광안동',
 '부산광역시-해운대구-우동',
 '경기도-부천시-범박동',
 '경기도-부천시-소사본동',
 '경기도-시흥시-신천동',
 '경상남도-진주시-하대동',
 '경기도-화성시-새솔동',
 '경기도-화성시-병점동',
 '경상북도-구미시-오태동',
 '경상남도-진주시-강남동',
 '대구광역시-수성구-두산동',
 '경상남도-진주시-호탄동',
 '전라북도-군산시-수송동',
 '경상북도-안동시-송현동',
 '경상남도-창원시 마산합포구-월포동',
 '경기도-수원시 장안구-천천동',
 '충청남도-홍성군-홍성읍',
 '제주특별자치도-서귀포시-강정동',
 '전라북도-전주시 완산구-중화산동2가',
 '경상북도-포항시 북구-흥해읍',
 '경기도-고양시 덕양구-성사동',
 '경기도-고양시 덕양구-주교동',
 '경기도-고양시 덕양구-토당동',
 '경기도-고양시 덕양구-행신동',
 '경기도-고양시 덕양구-화정동',
 '경기도-양평군-양평읍',
 '충청남도-서산시-성연면',
 '강원도-삼척시-남양동',
 '경기도-안산시 상록구-사동',
 '경상북도-구미시-진평동',
 '충청북도-제천시-교동',
 '경상북도-경주시-성건동',
 '경기도-성남시 수정구-신흥동',
 '경기도-수원시 권선구-호매실동',
 '대구광역시-동구-신암동',
 '서울특별시-성북구-동소문동1가',
 '경상북도-안동시-법상동',
 '서울특별시-마포구-연남동',
 '경상북도-경주시-용강동',
 '경기도-여주시-홍문동',
 '세종특별자치시-\\N-소담동',
 '경기도-파주시-문발동',
 '대구광역시-달서구-호산동',
 '전라북도-익산시-신동',
 '울산광역시-울주군-언양읍',
 '충청남도-천안시 서북구-쌍용동',
 '경상남도-김해시-흥동',
 '경기도-안산시 상록구-일동',
 '경상북도-경주시-현곡면',
 '경상북도-경주시-황성동',
 '경상북도-경주시-노동동',
 '경상북도-경주시-노서동',
 '경상북도-경주시-동부동',
 '경상북도-경주시-동천동',
 '경상북도-경주시-인왕동',
 '경상북도-경주시-충효동',
 '경상북도-경주시-황오동',
 '경상북도-경주시-석장동',
 '경상북도-경주시-외동읍',
 '경상북도-경주시-황남동',
 '서울특별시-영등포구-여의도동',
 '전라북도-군산시-산북동',
 '경상북도-경주시-사정동',
 '전라북도-군산시-신풍동',
 '전라북도-군산시-장재동',
 '서울특별시-노원구-공릉동',
 '경상남도-진주시-판문동',
 '경기도-동두천시-지행동',
 '대전광역시-동구-자양동',
 '경기도-동두천시-생연동',
 '강원도-속초시-중앙동',
 '전라북도-군산시-소룡동',
 '전라남도-광양시-중동',
 '전라북도-군산시-문화동',
 '전라북도-군산시-중앙로1가',
 '전라북도-군산시-조촌동',
 '광주광역시-서구-화정동',
 '광주광역시-북구-두암동',
 '전라북도-군산시-경암동',
 '충청북도-충주시-중앙탑면',
 '경기도-시흥시-장현동',
 '서울특별시-금천구-시흥동',
 '서울특별시-서대문구-남가좌동',
 '서울특별시-송파구-송파동',
 '서울특별시-송파구-문정동',
 '서울특별시-송파구-방이동',
 '서울특별시-송파구-가락동',
 '전라북도-군산시-미장동',
 '경기도-안양시 만안구-석수동',
 '경상북도-안동시-법흥동',
 '서울특별시-송파구-오금동',
 '서울특별시-송파구-석촌동',
 '전라남도-광양시-마동',
 '전라북도-군산시-대명동',
 '제주특별자치도-서귀포시-토평동',
 '제주특별자치도-제주시-월평동',
 '전라북도-군산시-경장동',
 '제주특별자치도-서귀포시-하효동',
 '전라북도-군산시-죽성동',
 '전라북도-군산시-미룡동',
 '경상북도-구미시-원평동',
 '경상북도-경주시-시래동',
 '경기도-고양시 일산서구-대화동',
 '경기도-시흥시-정왕동',
 '경기도-시흥시-대야동',
 '경기도-시흥시-월곶동',
 '전라북도-군산시-월명동',
 '경기도-시흥시-장곡동',
 '경기도-시흥시-능곡동',
 '제주특별자치도-서귀포시-법환동',
 '경상남도-창원시 의창구-봉곡동',
 '인천광역시-서구-청라동',
 '울산광역시-북구-신천동',
 '경상북도-경주시-구정동',
 '경기도-화성시-봉담읍',
 '경상북도-구미시-공단동',
 '경상북도-안동시-남문동',
 '서울특별시-강남구-삼성동',
 '경상북도-영주시-휴천동',
 '경상북도-영주시-영주동',
 '광주광역시-동구-학동',
 '대구광역시-중구-남산동',
 '경기도-화성시-능동',
 '서울특별시-마포구-성산동',
 '경상북도-구미시-황상동',
 '대구광역시-수성구-지산동',
 '경기도-부천시-역곡동',
 '서울특별시-금천구-가산동',
 '대구광역시-달성군-현풍읍',
 '경상북도-경주시-진현동',
 '경상북도-구미시-상모동',
 '제주특별자치도-제주시-구좌읍',
 '경상북도-칠곡군-석적읍',
 '제주특별자치도-서귀포시-대포동',
 '경기도-용인시 수지구-풍덕천동',
 '대구광역시-수성구-수성동4가',
 '서울특별시-마포구-동교동',
 '서울특별시-구로구-가리봉동',
 '대전광역시-유성구-지족동',
 '서울특별시-동작구-노량진동',
 '서울특별시-동작구-상도동',
 '서울특별시-동작구-흑석동',
 '부산광역시-해운대구-좌동',
 '전라북도-익산시-남중동',
 '전라북도-군산시-신창동',
 '경상북도-영천시-망정동',
 '경상북도-영천시-야사동',
 '경상북도-영천시-완산동',
 '경상북도-영천시-조교동',
 '전라북도-군산시-영동',
 '전라북도-군산시-장미동',
 '경상북도-영천시-문외동',
 '충청남도-서산시-수석동',
 '경상북도-영천시-과전동',
 '경상북도-경주시-성동동',
 '경상북도-칠곡군-북삼읍',
 '경상북도-안동시-당북동',
 '전라북도-군산시-미원동',
 '경상북도-영천시-창구동',
 '부산광역시-북구-덕천동',
 '충청남도-천안시 동남구-봉명동',
 '경상남도-창원시 마산합포구-신포동2가',
 '전라북도-전주시 완산구-효자동1가',
 '제주특별자치도-제주시-노형동',
 '제주특별자치도-서귀포시-서호동',
 '경상북도-경주시-구황동',
 '제주특별자치도-서귀포시-성산읍',
 '제주특별자치도-서귀포시-대정읍',
 '제주특별자치도-서귀포시-남원읍',
 '경상북도-경산시-진량읍',
 '서울특별시-마포구-서교동',
 '인천광역시-부평구-부개동',
 '인천광역시-부평구-부평동',
 '제주특별자치도-서귀포시-중문동',
 '인천광역시-부평구-갈산동',
 '경기도-포천시-선단동',
 '인천광역시-부평구-삼산동',
 '인천광역시-서구-불로동',
 '경상북도-구미시-고아읍',
 '경기도-양주시-덕계동',
 '경기도-양주시-옥정동',
 '경기도-양주시-삼숭동',
 '경상남도-창원시 마산합포구-남성동',
 '경상남도-진주시-금산면',
 '경기도-양주시-광사동',
 '경기도-김포시-고촌읍',
 '서울특별시-서초구-반포동',
 '전라북도-군산시-명산동',
 '제주특별자치도-제주시-한림읍',
 '서울특별시-서초구-서초동',
 '서울특별시-강남구-논현동',
 '서울특별시-강남구-신사동',
 '서울특별시-강남구-대치동',
 '서울특별시-강남구-역삼동',
 '서울특별시-강남구-청담동',
 '서울특별시-서초구-양재동',
 '서울특별시-서초구-잠원동',
 '서울특별시-강남구-도곡동',
 '광주광역시-동구-금남로5가',
 '서울특별시-강남구-개포동',
 '경기도-부천시-상동',
 '경상남도-양산시-물금읍',
 '경기도-양주시-덕정동',
 '제주특별자치도-제주시-건입동',
 '대전광역시-동구-판암동',
 '대전광역시-동구-용운동',
 '부산광역시-기장군-정관읍',
 '경기도-구리시-갈매동',
 '대전광역시-동구-신흥동',
 '경기도-화성시-남양읍',
 '경상남도-창원시 성산구-상남동',
 '세종특별자치시-\\N-다정동',
 '제주특별자치도-제주시-이도이동',
 '경기도-부천시-삼정동',
 '전라북도-군산시-동흥남동',
 '경기도-안산시 상록구-이동',
 '경기도-부천시-약대동',
 '경기도-부천시-중동',
 '경기도-부천시-원미동',
 '경기도-부천시-춘의동',
 '경기도-부천시-심곡동',
 '경기도-부천시-도당동',
 '경기도-부천시-송내동',
 '제주특별자치도-서귀포시-보목동',
 '경기도-부천시-심곡본동',
 '인천광역시-연수구-동춘동',
 '경기도-부천시-소사동',
 '경상남도-진주시-남성동',
 '전라북도-군산시-구암동',
 '제주특별자치도-서귀포시-안덕면',
 '제주특별자치도-제주시-도두일동',
 '경기도-부천시-내동',
 '경상북도-안동시-서부동',
 '인천광역시-서구-가좌동',
 '전라남도-광양시-도이동',
 '경상북도-경산시-중방동',
 '충청북도-청주시 청원구-오창읍',
 '경상남도-김해시-전하동',
 '경기도-동두천시-송내동',
 '대전광역시-서구-갈마동',
 '경상북도-안동시-북문동',
 '제주특별자치도-서귀포시-상효동',
 '경기도-동두천시-보산동',
 '대전광역시-서구-월평동',
 '부산광역시-연제구-연산동',
 '세종특별자치시-\\N-고운동',
 '서울특별시-서초구-방배동',
 '경기도-시흥시-계수동',
 '서울특별시-동작구-사당동',
 '전라북도-군산시-해망동',
 '경기도-부천시-오정동',
 '경기도-동두천시-동두천동',
 '광주광역시-동구-용산동',
 '서울특별시-영등포구-문래동3가',
 '서울특별시-영등포구-당산동4가',
 '서울특별시-영등포구-당산동5가',
 '제주특별자치도-제주시-애월읍',
 '서울특별시-영등포구-영등포동7가',
 '전라북도-군산시-금동',
 '서울특별시-영등포구-당산동',
 '서울특별시-영등포구-양평동4가',
 '서울특별시-영등포구-영등포동8가',
 '서울특별시-용산구-동빙고동',
 '서울특별시-동작구-상도1동',
 '경기도-용인시 기흥구-중동',
 '경기도-여주시-강천면',
 '경기도-용인시 처인구-포곡읍',
 '대전광역시-대덕구-비래동',
 '대전광역시-유성구-봉명동',
 '부산광역시-동래구-명륜동',
 '경상남도-진주시-충무공동',
 '대구광역시-동구-신천동',
 '서울특별시-영등포구-당산동3가',
 '서울특별시-관악구-남현동',
 '전라북도-군산시-영화동',
 '충청북도-청주시 흥덕구-가경동',
 '경기도-파주시-문산읍',
 '전라북도-군산시-신영동',
 '대구광역시-북구-침산동',
 '경상북도-안동시-성곡동',
 '경상남도-창원시 마산합포구-중성동',
 '경기도-안양시 동안구-호계동',
 '전라북도-군산시-서흥남동',
 '경기도-안양시 동안구-평촌동',
 '전라남도-여수시-소라면',
 '전라남도-여수시-소호동',
 '전라남도-여수시-웅천동',
 '서울특별시-동대문구-장안동',
 '전라남도-광양시-광양읍',
 '전라남도-여수시-신기동',
 '전라남도-여수시-안산동',
 '전라남도-여수시-여서동',
 '전라남도-여수시-학동',
 '경기도-안양시 동안구-관양동',
 '제주특별자치도-서귀포시-표선면',
 '서울특별시-구로구-항동',
 '경상북도-경산시-자인면',
 '전라남도-여수시-화장동',
 '전라남도-여수시-교동',
 '제주특별자치도-제주시-용담이동',
 '충청북도-제천시-남천동',
 '전라남도-여수시-덕충동',
 '경상북도-안동시-명륜동',
 '제주특별자치도-제주시-도련일동',
 '경기도-광주시-태전동',
 '대구광역시-수성구-황금동',
 '광주광역시-북구-각화동',
 '대구광역시-수성구-상동',
 '경상북도-경산시-하양읍',
 '전라북도-군산시-중앙로3가',
 '대구광역시-수성구-범물동',
 '경기도-광주시-목동',
 '경상북도-칠곡군-왜관읍',
 '광주광역시-동구-산수동',
 '경상남도-거제시-고현동',
 '경기도-평택시-지산동',
 '대구광역시-달서구-본리동',
 '경기도-광주시-중대동',
 '대전광역시-동구-대동',
 '경기도-평택시-서정동',
 '경기도-고양시 덕양구-원흥동',
 '경기도-고양시 덕양구-삼송동',
 '제주특별자치도-서귀포시-도순동',
 '제주특별자치도-서귀포시-색달동',
 '경기도-고양시 덕양구-도내동',
 '대전광역시-동구-용전동',
 '서울특별시-노원구-중계동',
 '경기도-광주시-장지동',
 '경기도-고양시 덕양구-용두동',
 '제주특별자치도-서귀포시-하원동',
 '전라북도-군산시-옥산면',
 '경기도-남양주시-와부읍',
 '전라북도-군산시-삼학동',
 '경기도-김포시-양촌읍',
 '제주특별자치도-서귀포시-호근동',
 '경기도-평택시-신장동',
 '경상북도-영천시-금노동',
 '경상남도-진주시-봉래동',
 '경상남도-거제시-장평동',
 '경기도-고양시 덕양구-동산동',
 '제주특별자치도-서귀포시-신효동',
 '경상남도-거제시-수월동',
 '경상남도-거제시-옥포동',
 '경상남도-거제시-양정동',
 '충청북도-제천시-왕암동',
 '경기도-고양시 일산동구-성석동',
 '전라북도-익산시-모현동1가',
 '경기도-동두천시-상패동',
 '경상북도-안동시-안기동',
 '경상북도-안동시-운흥동',
 '전라북도-군산시-금광동',
 '경상북도-안동시-안흥동',
 '대전광역시-동구-삼성동',
 '경기도-수원시 팔달구-화서동',
 '경기도-수원시 권선구-구운동',
 '경기도-용인시 처인구-모현읍',
 '충청북도-제천시-서부동',
 '경기도-포천시-신북면',
 '제주특별자치도-제주시-오라이동',
 '전라북도-군산시-개정면',
 '서울특별시-영등포구-당산동1가',
 '서울특별시-강동구-성내동',
 '경기도-동두천시-안흥동',
 '경기도-평택시-이충동',
 '충청북도-음성군-감곡면',
 '전라북도-군산시-서수면',
 '경상북도-문경시-모전동',
 '서울특별시-강동구-천호동',
 '서울특별시-강동구-암사동',
 '서울특별시-송파구-잠실동',
 '서울특별시-강동구-길동',
 '경기도-성남시 수정구-태평동',
 '경기도-평택시-청북읍',
 '부산광역시-사하구-신평동',
 '경상북도-김천시-성내동',
 '경상북도-김천시-신음동',
 '서울특별시-강동구-고덕동',
 '경기도-오산시-원동',
 '경기도-성남시 수정구-복정동',
 '경기도-성남시 중원구-금광동',
 '경기도-성남시 중원구-성남동',
 '경기도-성남시 중원구-중앙동',
 '경기도-성남시 중원구-상대원동',
 '경기도-성남시 중원구-은행동',
 '경기도-성남시 수정구-수진동',
 '경기도-광명시-노온사동',
 '경기도-평택시-세교동',
 '경기도-성남시 수정구-양지동',
 '경기도-성남시 중원구-하대원동',
 '경상북도-문경시-점촌동',
 '서울특별시-송파구-삼전동',
 '충청북도-단양군-매포읍',
 '경기도-하남시-초이동',
 '경상북도-김천시-삼락동',
 '경상북도-김천시-평화동',
 '경기도-평택시-독곡동',
 '경상북도-영천시-언하동',
 '경상북도-안동시-운안동',
 '서울특별시-중랑구-묵동',
 '경상남도-창원시 마산합포구-성호동',
 '경기도-포천시-일동면',
 '서울특별시-중랑구-중화동',
 '경상북도-김천시-부곡동',
 '인천광역시-부평구-일신동',
 '전라북도-김제시-요촌동',
 '전라남도-나주시-대호동',
 '경상남도-창원시 마산합포구-교방동',
 '전라남도-나주시-송월동',
 '전라북도-군산시-옥구읍',
 '전라북도-군산시-중앙로2가',
 '경기도-고양시 덕양구-신원동',
 '전라남도-나주시-성북동',
 '경상남도-진주시-내동면',
 '충청남도-서산시-지곡면',
 '경상남도-창원시 마산합포구-창동',
 '서울특별시-노원구-월계동',
 '경상북도-경산시-중산동',
 '충청남도-서산시-석남동',
 '대구광역시-수성구-신매동',
 '대전광역시-동구-홍도동',
 '대구광역시-수성구-시지동',
 '대전광역시-대덕구-송촌동',
 '경상북도-김천시-교동',
 '인천광역시-미추홀구-주안동',
 '강원도-강릉시-송정동',
 '경상북도-문경시-흥덕동',
 '충청북도-괴산군-괴산읍',
 '경기도-이천시-장호원읍',
 '전라북도-군산시-오식도동',
 '경상북도-경산시-와촌면',
 '전라남도-나주시-금계동',
 '서울특별시-강동구-명일동',
 '충청남도-서산시-잠홍동',
 '경기도-용인시 처인구-유방동',
 '서울특별시-영등포구-영등포동3가',
 '충청남도-아산시-용화동',
 '경상남도-사천시-송포동',
 '충청북도-충주시-교현동',
 '경상북도-안동시-목성동',
 '충청북도-제천시-봉양읍',
 '광주광역시-북구-용봉동',
 '광주광역시-북구-중흥동',
 '경기도-포천시-군내면',
 '충청남도-논산시-지산동',
 '광주광역시-북구-신용동',
 '충청남도-논산시-취암동',
 '충청남도-논산시-대교동',
 '광주광역시-북구-연제동',
 '경상북도-경주시-마동',
 '광주광역시-북구-용두동',
 '대구광역시-달서구-상인동',
 '대구광역시-동구-방촌동',
 '대구광역시-달서구-송현동',
 '대구광역시-달서구-월성동',
 '대구광역시-달서구-도원동',
 '대구광역시-동구-봉무동',
 '충청남도-논산시-강산동',
 '대구광역시-남구-대명동',
 '대구광역시-달서구-대천동',
 '전라북도-군산시-비응도동',
 '제주특별자치도-서귀포시-회수동',
 '충청남도-논산시-반월동',
 '충청북도-단양군-단양읍',
 '충청남도-논산시-내동',
 '전라남도-나주시-남내동',
 '광주광역시-북구-문흥동',
 '대전광역시-중구-선화동',
 '광주광역시-북구-양산동',
 '충청남도-아산시-온천동',
 '대전광역시-중구-대흥동',
 '충청남도-논산시-부창동',
 '대전광역시-동구-가오동',
 '충청남도-아산시-풍기동',
 '충청남도-아산시-둔포면',
 '충청남도-서산시-인지면',
 '경기도-안산시 단원구-초지동',
 '경상북도-김천시-응명동',
 '광주광역시-남구-방림동',
 '충청북도-충주시-문화동',
 '울산광역시-북구-연암동',
 '전라남도-나주시-남평읍',
 '울산광역시-중구-장현동',
 '전라북도-군산시-둔율동',
 '경기도-성남시 분당구-야탑동',
 '전라남도-나주시-금성동',
 '대전광역시-동구-소제동',
 '충청남도-아산시-모종동',
 '충청북도-충주시-호암동',
 '경상북도-문경시-영신동',
 '충청북도-충주시-용산동',
 '경상북도-김천시-모암동',
 '경기도-성남시 중원구-여수동',
 '충청북도-충주시-연수동',
 '전라북도-군산시-평화동',
 '전라북도-군산시-개복동',
 '제주특별자치도-제주시-외도일동',
 '대전광역시-서구-탄방동',
 '충청북도-충주시-성내동',
 '울산광역시-북구-중산동',
 '충청북도-충주시-성서동',
 '강원도-철원군-서면',
 '경기도-시흥시-물왕동',
 '경기도-오산시-청학동',
 '전라북도-군산시-중동',
 '전라북도-군산시-금암동',
 '광주광역시-북구-본촌동',
 '경상북도-예천군-호명면',
 '서울특별시-용산구-서계동',
 '경기도-이천시-창전동',
 '충청북도-증평군-증평읍',
 '경기도-이천시-송정동',
 '경기도-이천시-중리동',
 '제주특별자치도-제주시-조천읍',
 '경상북도-안동시-상아동',
 '서울특별시-중구-만리동1가',
 '인천광역시-계양구-동양동',
 '전라남도-나주시-죽림동',
 '서울특별시-마포구-공덕동',
 '부산광역시-연제구-거제동',
 '경상북도-김천시-남산동',
 '경기도-이천시-관고동',
 '제주특별자치도-서귀포시-월평동',
 '서울특별시-용산구-청파동1가',
 '전라북도-군산시-사정동',
 '서울특별시-영등포구-당산동2가',
 '경상북도-안동시-송천동',
 '전라북도-군산시-오룡동',
 '충청북도-충주시-칠금동',
 '경기도-광주시-오포읍',
 '울산광역시-울주군-삼남면',
 '전라남도-나주시-삼도동',
 '전라북도-정읍시-수성동',
 '전라남도-나주시-서내동',
 '부산광역시-강서구-녹산동',
 '서울특별시-중구-만리동2가',
 '전라북도-정읍시-상동',
 '경기도-안산시 단원구-고잔동',
 '서울특별시-용산구-동자동',
 '울산광역시-울주군-삼남읍',
 '경기도-안산시 상록구-부곡동',
 '제주특별자치도-서귀포시-하예동',
 '전라북도-정읍시-시기동',
 '경기도-양주시-고암동',
 '경상북도-안동시-풍천면',
 '경기도-용인시 처인구-남사읍',
 '경기도-의정부시-산곡동',
 '서울특별시-용산구-후암동',
 '대구광역시-달성군-구지면',
 '서울특별시-서대문구-충정로3가',
 '서울특별시-영등포구-문래동5가',
 '경기도-포천시-어룡동',
 '전라북도-군산시-내흥동',
 '전라북도-군산시-창성동',
 '인천광역시-계양구-장기동',
 '전라남도-목포시-옥암동',
 '서울특별시-중구-중림동',
 '광주광역시-광산구-월계동',
 '대구광역시-달성군-유가읍',
 '경상남도-사천시-사천읍',
 '광주광역시-광산구-쌍암동',
 '서울특별시-용산구-청파동2가',
 '경기도-의정부시-고산동',
 '경기도-광주시-경안동',
 '충청남도-천안시 동남구-신방동',
 '경기도-광주시-역동',
 '경기도-광주시-탄벌동',
 '충청남도-천안시 서북구-불당동',
 '경기도-양주시-은현면',
 '충청남도-천안시 동남구-목천읍',
 '경기도-성남시 중원구-도촌동',
 '경기도-광주시-송정동',
 '경기도-양주시-봉양동',
 '전라북도-정읍시-농소동',
 '경기도-용인시 처인구-이동읍',
 '광주광역시-광산구-산월동',
 '울산광역시-울주군-온산읍',
 '경상북도-안동시-대석동',
 '서울특별시-중랑구-신내동',
 '경기도-군포시-부곡동',
 '경기도-김포시-구래동',
 '경기도-평택시-현덕면',
 '제주특별자치도-제주시-도두이동',
 '경기도-의왕시-초평동',
 '경상북도-칠곡군-기산면',
 '경기도-의왕시-삼동',
 '경기도-파주시-금촌동',
 '강원도-철원군-동송읍',
 '경기도-양주시-회정동',
 '경기도-양주시-광적면',
 '인천광역시-미추홀구-도화동',
 '전라남도-나주시-과원동',
 '경기도-의왕시-월암동',
 '경기도-평택시-장당동',
 '경기도-화성시-우정읍',
 '서울특별시-용산구-갈월동',
 '울산광역시-울주군-온양읍',
 '서울특별시-강남구-자곡동',
 '경기도-화성시-장안면',
 '충청북도-제천시-두학동',
 '경기도-시흥시-매화동',
 '서울특별시-성동구-마장동',
 '서울특별시-강북구-수유동',
 '경기도-안양시 만안구-안양동',
 '대구광역시-북구-사수동',
 '서울특별시-중구-신당동',
 '경기도-파주시-파주읍',
 '경기도-안양시 만안구-박달동',
 '서울특별시-노원구-하계동',
 '경기도-군포시-도마교동',
 '부산광역시-남구-용호동',
 '부산광역시-남구-대연동',
 '충청북도-충주시-금릉동',
 '전라남도-광양시-광영동',
 '충청북도-충주시-안림동',
 '부산광역시-남구-용당동',
 '부산광역시-수영구-남천동',
 '세종특별자치시-\\N-조치원읍',
 '충청북도-충주시-성남동',
 '충청남도-천안시 동남구-원성동',
 '경기도-시흥시-미산동',
 '강원도-원주시-지정면',
 '경기도-안산시 상록구-월피동',
 '경기도-화성시-반송동',
 '제주특별자치도-제주시-일도이동',
 '울산광역시-북구-매곡동',
 '제주특별자치도-제주시-도남동',
 '울산광역시-북구-천곡동',
 '경상북도-의성군-의성읍',
 '경기도-이천시-안흥동',
 '경기도-시흥시-포동',
 '대구광역시-북구-금호동',
 '충청남도-천안시 동남구-용곡동',
 '경상북도-영천시-문내동',
 '경상북도-봉화군-봉화읍',
 '서울특별시-용산구-한남동',
 '경기도-부천시-고강동',
 '대구광역시-북구-동천동',
 '경기도-부천시-원종동',
 '대구광역시-북구-산격동',
 '대구광역시-북구-태전동',
 '전라북도-익산시-부송동',
 '전라북도-익산시-영등동',
 '전라북도-익산시-동산동',
 '대구광역시-중구-동성로2가',
 '대구광역시-중구-덕산동',
 '대구광역시-중구-삼덕동1가',
 '경기도-이천시-증포동',
 '경기도-시흥시-광석동',
 '경기도-안산시 상록구-수암동',
 '경기도-양주시-남면',
 '경기도-시흥시-도창동',
 '경기도-이천시-신둔면',
 '경기도-이천시-부발읍',
 '경기도-양주시-산북동',
 '강원도-춘천시-후평동',
 '경기도-양주시-장흥면',
 '경기도-양주시-고읍동',
 '강원도-춘천시-동내면',
 '강원도-춘천시-석사동',
 '강원도-춘천시-퇴계동',
 '강원도-춘천시-효자동',
 '강원도-춘천시-소양로2가',
 '강원도-춘천시-요선동',
 '대전광역시-대덕구-오정동']

In [12]:
df.지역.nunique()

913

all_areas : 모든 개별 지역('시도-시군구-읍면동')의 이름을 담고있는 list
entire_date : 우리가 커버하는 기간+시간 전체의 range 데이터프레임(배달건수 정보의 기준이 되는 개별 cell 단위) 

df['date_time']이랑 entire_date['date_time']이랑 포맷 일치하게 맞춰뒀음. 

for문 돌려서 all_area에서 하나씩 꺼내와서
해당 area랑 df['지역']이 일치하는 df을 걸러내서 date_time이랑 머지하면 됨

### 모든 고유 지역에는 18289개의 레코드가 있어야함

In [13]:
df['date_time'] = pd.to_datetime(df['date_time'], format="%Y-%m-%d")
df

         배달건수                지역           date_time
0           1        강원도-속초시-교동 2019-08-01 00:00:00
1           4  경기도-고양시 일산동구-마두동 2019-08-01 00:00:00
2          28  경기도-고양시 일산동구-백석동 2019-08-01 00:00:00
3           3  경기도-고양시 일산동구-식사동 2019-08-01 00:00:00
4           4  경기도-고양시 일산동구-장항동 2019-08-01 00:00:00
...       ...               ...                 ...
2382976     6  충청남도-천안시 서북구-쌍용동 2021-08-31 23:00:00
2382977     6      충청북도-제천시-신백동 2021-08-31 23:00:00
2382978     2      충청북도-제천시-신월동 2021-08-31 23:00:00
2382979     1      충청북도-제천시-천남동 2021-08-31 23:00:00
2382980     4      충청북도-제천시-하소동 2021-08-31 23:00:00

[2382981 rows x 3 columns]

In [14]:
entire_date.columns=['date_time']
entire_date

                date_time
0     2019-08-01 00:00:00
1     2019-08-01 01:00:00
2     2019-08-01 02:00:00
3     2019-08-01 03:00:00
4     2019-08-01 04:00:00
...                   ...
18284 2021-08-31 20:00:00
18285 2021-08-31 21:00:00
18286 2021-08-31 22:00:00
18287 2021-08-31 23:00:00
18288 2021-09-01 00:00:00

[18289 rows x 1 columns]

In [146]:
# for문 돌려서 all_area에서 하나씩 꺼내와서 
# 해당 area랑 df['지역']이 일치하는 df을 걸러내서 date_time이랑 머지하면 됨

# for i in range(len(all_areas)):
#     area = all_areas[i]
#     df[df['지역']== area]

In [15]:
# 일단 하나만 테스트로 해보자
# '경기도-고양시 일산동구-마두동'이랑 entire_date랑 머지해보자
test_area = df[df['지역']=='충청북도-충주시-칠금동']
# test_area
merge_test = pd.merge(test_area, entire_date, how='right', on='date_time')
merge_test['배달건수'] = merge_test['배달건수'].fillna(0)
merge_test['지역'] = merge_test['지역'].fillna(method='ffill')
merge_test['지역'] = merge_test['지역'].fillna(method='bfill')
merge_test
# merge_test[merge_test.지역.notnull()]
# merge_test[merge_test.지역.isnull()]

       배달건수            지역           date_time
0       0.0  충청북도-충주시-칠금동 2019-08-01 00:00:00
1       0.0  충청북도-충주시-칠금동 2019-08-01 01:00:00
2       0.0  충청북도-충주시-칠금동 2019-08-01 02:00:00
3       0.0  충청북도-충주시-칠금동 2019-08-01 03:00:00
4       0.0  충청북도-충주시-칠금동 2019-08-01 04:00:00
...     ...           ...                 ...
18284   0.0  충청북도-충주시-칠금동 2021-08-31 20:00:00
18285   0.0  충청북도-충주시-칠금동 2021-08-31 21:00:00
18286   0.0  충청북도-충주시-칠금동 2021-08-31 22:00:00
18287   0.0  충청북도-충주시-칠금동 2021-08-31 23:00:00
18288   0.0  충청북도-충주시-칠금동 2021-09-01 00:00:00

[18289 rows x 3 columns]

In [16]:
merged_areas_df = merge_test
merged_areas_df

       배달건수            지역           date_time
0       0.0  충청북도-충주시-칠금동 2019-08-01 00:00:00
1       0.0  충청북도-충주시-칠금동 2019-08-01 01:00:00
2       0.0  충청북도-충주시-칠금동 2019-08-01 02:00:00
3       0.0  충청북도-충주시-칠금동 2019-08-01 03:00:00
4       0.0  충청북도-충주시-칠금동 2019-08-01 04:00:00
...     ...           ...                 ...
18284   0.0  충청북도-충주시-칠금동 2021-08-31 20:00:00
18285   0.0  충청북도-충주시-칠금동 2021-08-31 21:00:00
18286   0.0  충청북도-충주시-칠금동 2021-08-31 22:00:00
18287   0.0  충청북도-충주시-칠금동 2021-08-31 23:00:00
18288   0.0  충청북도-충주시-칠금동 2021-09-01 00:00:00

[18289 rows x 3 columns]

In [17]:
for i in range(len(all_areas)):
    area = all_areas[i]
    merge_area = df[df['지역']==area]
    merged_area = pd.merge(merge_area, entire_date, how='outer', on='date_time')
    merged_area['배달건수'] = merged_area['배달건수'].fillna(0)
    merged_area['지역'] = merged_area['지역'].fillna(method='ffill')
    merged_area['지역'] = merged_area['지역'].fillna(method='bfill')
    merged_areas_df = merged_areas_df.append(merged_area)
merged_areas_df

       배달건수             지역           date_time
0       0.0   충청북도-충주시-칠금동 2019-08-01 00:00:00
1       0.0   충청북도-충주시-칠금동 2019-08-01 01:00:00
2       0.0   충청북도-충주시-칠금동 2019-08-01 02:00:00
3       0.0   충청북도-충주시-칠금동 2019-08-01 03:00:00
4       0.0   충청북도-충주시-칠금동 2019-08-01 04:00:00
...     ...            ...                 ...
18284   0.0  대전광역시-대덕구-오정동 2021-08-31 19:00:00
18285   0.0  대전광역시-대덕구-오정동 2021-08-31 21:00:00
18286   0.0  대전광역시-대덕구-오정동 2021-08-31 22:00:00
18287   0.0  대전광역시-대덕구-오정동 2021-08-31 23:00:00
18288   0.0  대전광역시-대덕구-오정동 2021-09-01 00:00:00

[16716146 rows x 3 columns]

In [22]:
# 전체 레코드 갯수는 개별지역(913개) * 전체일수(762일)*시간대(24)로 나와야함 
# 마지막 2021-09-01 00:00:00시 하나가 더 들어가서 18289
18289*914 
#16697857
#16716146
# ffill로 안 채워지는 애들이 많이 있군...얘네는 bfill로 채워야하네

16716146

In [18]:
df = merged_areas_df.drop_duplicates()

In [19]:
df.groupby('지역').size()

지역
강원도-강릉시-교동       18289
강원도-강릉시-송정동      18289
강원도-삼척시-교동       18289
강원도-삼척시-남양동      18289
강원도-속초시-교동       18289
                 ...
충청북도-충주시-연수동     18289
충청북도-충주시-용산동     18289
충청북도-충주시-중앙탑면    18289
충청북도-충주시-칠금동     18289
충청북도-충주시-호암동     18289
Length: 913, dtype: int64

In [21]:
df.to_csv('/Users/seulalee/OneDrive/MyStudy/210816_엘리스AI트랙/TeamProject1/Team11_NaplessRabbit/project-template/cleaned_data/entire_datetime.csv')

# 1. 이제 다시 ['지역']을 ['광역시도'], ['시군구'],[읍면동] 으로 나누기
# 2. ['date_time']을 'date'와 'time'으로 나누기 
# 3. 공휴일 다시 추가하기

In [18]:
df.dtypes

배달건수                float64
지역                   object
date_time    datetime64[ns]
dtype: object

In [22]:
df['date'] = df['date_time'].dt.date

<ipython-input-22-9d4afb82e295>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['date'] = df['date_time'].dt.date

In [23]:
df['time'] = df['date_time'].dt.time
df

<ipython-input-23-915383e59d6a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time'] = df['date_time'].dt.time

       배달건수             지역           date_time        date      time
0       0.0   충청북도-충주시-칠금동 2019-08-01 00:00:00  2019-08-01  00:00:00
1       0.0   충청북도-충주시-칠금동 2019-08-01 01:00:00  2019-08-01  01:00:00
2       0.0   충청북도-충주시-칠금동 2019-08-01 02:00:00  2019-08-01  02:00:00
3       0.0   충청북도-충주시-칠금동 2019-08-01 03:00:00  2019-08-01  03:00:00
4       0.0   충청북도-충주시-칠금동 2019-08-01 04:00:00  2019-08-01  04:00:00
...     ...            ...                 ...         ...       ...
18284   0.0  대전광역시-대덕구-오정동 2021-08-31 19:00:00  2021-08-31  19:00:00
18285   0.0  대전광역시-대덕구-오정동 2021-08-31 21:00:00  2021-08-31  21:00:00
18286   0.0  대전광역시-대덕구-오정동 2021-08-31 22:00:00  2021-08-31  22:00:00
18287   0.0  대전광역시-대덕구-오정동 2021-08-31 23:00:00  2021-08-31  23:00:00
18288   0.0  대전광역시-대덕구-오정동 2021-09-01 00:00:00  2021-09-01  00:00:00

[16697857 rows x 5 columns]

In [24]:
%%time
df['광역시도'] = df.지역.str.split('-').str[0]
df['시군구'] = df.지역.str.split('-').str[1]
df['읍면동'] = df.지역.str.split('-').str[2]
df.drop(['date_time','지역'], axis=1)
df.to_csv('/Users/seulalee/OneDrive/MyStudy/210816_엘리스AI트랙/TeamProject1/Team11_NaplessRabbit/project-template/cleaned_data/entire_datetime_2.csv')

df

<timed exec>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<timed exec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<timed exec>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

CPU times: user 2min 26s, sys: 1min 30s, total: 3min 56s
Wall time: 4min 46s

,배달건수,지역,date_time,date,time,광역시도,시군구,읍면동
0,0.0,충청북도-충주시-칠금동,2019-08-01 00:00:00,2019-08-01,00:00:00,충청북도,충주시,칠금동
1,0.0,충청북도-충주시-칠금동,2019-08-01 01:00:00,2019-08-01,01:00:00,충청북도,충주시,칠금동
2,0.0,충청북도-충주시-칠금동,2019-08-01 02:00:00,2019-08-01,02:00:00,충청북도,충주시,칠금동
3,0.0,충청북도-충주시-칠금동,2019-08-01 03:00:00,2019-08-01,03:00:00,충청북도,충주시,칠금동
4,0.0,충청북도-충주시-칠금동,2019-08-01 04:00:00,2019-08-01,04:00:00,충청북도,충주시,칠금동
...,...,...,...,...,...,...,...,...
18284,0.0,대전광역시-대덕구-오정동,2021-08-31 19:00:00,2021-08-31,19:00:00,대전광역시,대덕구,오정동
18285,0.0,대전광역시-대덕구-오정동,2021-08-31 21:00:00,2021-08-31,21:00:00,대전광역시,대덕구,오정동
18286,0.0,대전광역시-대덕구-오정동,2021-08-31 22:00:00,2021-08-31,22:00:00,대전광역시,대덕구,오정동
18287,0.0,대전광역시-대덕구-오정동,2021-08-31 23:00:00,2021-08-31,23:00:00,대전광역시,대덕구,오정동
18288,0.0,대전광역시-대덕구-오정동,2021-09-01 00:00:00,2021-09-01,00:00:00,대전광역시,대덕구,오정동

In [25]:
%%time

df.drop(['date_time','지역'], axis=1, inplace=True)
df.to_csv('/Users/seulalee/OneDrive/MyStudy/210816_엘리스AI트랙/TeamProject1/Team11_NaplessRabbit/project-template/cleaned_data/entire_datetime_3.csv')
df

/Users/seulalee/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

CPU times: user 52 s, sys: 17.4 s, total: 1min 9s
Wall time: 1min 18s

       배달건수        date      time   광역시도  시군구  읍면동
0       0.0  2019-08-01  00:00:00   충청북도  충주시  칠금동
1       0.0  2019-08-01  01:00:00   충청북도  충주시  칠금동
2       0.0  2019-08-01  02:00:00   충청북도  충주시  칠금동
3       0.0  2019-08-01  03:00:00   충청북도  충주시  칠금동
4       0.0  2019-08-01  04:00:00   충청북도  충주시  칠금동
...     ...         ...       ...    ...  ...  ...
18284   0.0  2021-08-31  19:00:00  대전광역시  대덕구  오정동
18285   0.0  2021-08-31  21:00:00  대전광역시  대덕구  오정동
18286   0.0  2021-08-31  22:00:00  대전광역시  대덕구  오정동
18287   0.0  2021-08-31  23:00:00  대전광역시  대덕구  오정동
18288   0.0  2021-09-01  00:00:00  대전광역시  대덕구  오정동

[16697857 rows x 6 columns]

In [ ]:
df.dtypes